// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW2_7YrRhTv6e_apmZquu66EsfivfwcrU',
    appId: '1:906802971217:web:e5c18d6ff00b288b922e70',
    messagingSenderId: '906802971217',
    projectId: 'shopease-be4b3',
    authDomain: 'shopease-be4b3.firebaseapp.com',
    storageBucket: 'shopease-be4b3.appspot.com',
    measurementId: 'G-8JW2VX1KS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHskwzb-C5CaW0zRAdcIbVuNUWlud6fto',
    appId: '1:906802971217:android:4076eb45503f941e922e70',
    messagingSenderId: '906802971217',
    projectId: 'shopease-be4b3',
    storageBucket: 'shopease-be4b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ7LCAzod4zBDk1XneX37-6T2CxIrKLL0',
    appId: '1:906802971217:ios:7a09e97119d728a7922e70',
    messagingSenderId: '906802971217',
    projectId: 'shopease-be4b3',
    storageBucket: 'shopease-be4b3.appspot.com',
    iosBundleId: 'com.example.shopease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ7LCAzod4zBDk1XneX37-6T2CxIrKLL0',
    appId: '1:906802971217:ios:7a09e97119d728a7922e70',
    messagingSenderId: '906802971217',
    projectId: 'shopease-be4b3',
    storageBucket: 'shopease-be4b3.appspot.com',
    iosBundleId: 'com.example.shopease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW2_7YrRhTv6e_apmZquu66EsfivfwcrU',
    appId: '1:906802971217:web:6799c55de1e168db922e70',
    messagingSenderId: '906802971217',
    projectId: 'shopease-be4b3',
    authDomain: 'shopease-be4b3.firebaseapp.com',
    storageBucket: 'shopease-be4b3.appspot.com',
    measurementId: 'G-KYKWM8Z47V',
  );
}
